version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-nextjs_admin}
    restart: always
    environment:
      - NODE_ENV=production
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_POST_LOGOUT_REDIRECT_URI=${AUTH0_POST_LOGOUT_REDIRECT_URI}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - APP_BASE_URL=${APP_BASE_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    ports:
      - "${PORT:-3000}:3000"